site_name: IPtables Add-on for Splunk Documentation
edit_uri: edit/master/docs/
repo_url: https://github.com/ZachChristensen28/TA-linux_iptables
repo_name: ZachChristensen28/TA-linux_iptables
site_description: >-
  Welcome to the Home of the IPtables Add-on for Splunk documentation. The Iptables Add-on allows Splunk data administrators to map netfilter events to the CIM enabling the data to be used with other Splunk Apps.

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.annotate
    # - toc.integrate
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zachary-christensen28/
    - icon: fontawesome/brands/github
      link: https://github.com/ZachChristensen28
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ZachTheSplunker

copyright: Copyright &copy; 2023 ZachTheSplunker

nav:
  - Home: index.md
  - Getting Started:
      - Prepare Logs for Splunk: getting-started/prepare-logs-for-splunk.md
      - Where to Install: getting-started/where-to-install.md
      - Configure Inputs:
          - Configure Universal Forwarder: getting-started/configure-inputs/configure-inputs.md
      - Troubleshooting:
          - Troubleshoot Monitoring Inputs: getting-started/troubleshooting/troubleshoot-inputs.md
  - Guides:
      - Custom Log Prefix: guides/guide-custom-log-prefix.md
  - Reference:
      - Sourectypes: reference/reference-sourcetypes.md
      - Lookup Tables: reference/reference-lookups.md
      - Changelog:
          - Release Notes: reference/releases/index.md
          - Release History: reference/releases/release-history.md
