name: Docs
on:
  push:
    branches:
      - master
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"

jobs:
  call-docs-workflow:
    uses: ZachChristensen28/splunk-github-wfa/.github/workflows/docs.yml@e96bdc58732819aa2a1f2a03cb8794c92cacd9f6
    with:
      config-path: docs/requirements.txt
